### ISSUE TITLE
FontData for Builtin Fonts

### ISSUE THREAD

**Issue by ta-vroom** [sharazam/printpdf#121]
Is this possible? I was trying to get text width.

**Comment by fschutt** [comment]
No, because `BuiltinFonts` are fonts like Times New Roman, and I can't really distribute them without breaking font licensing agreements (these are usually proprietary fonts).

You can use https://crates.io/crates/rust-fontconfig or a similar crates such as font-loader, etc. to look for the font on the users computer.

**Comment by ta-vroom** [comment]
Oh, thank you for writing that package.

Also of note: apparently Windows uses Arial to render the Helvetica font.
